# Unified Slack Monitor Configuration
# Works with both standard and smart monitors

# Channels to monitor (supports wildcards)
channels:
  - "cslog-alertas*"  # All channels starting with cslog-alertas

# Channel to send summary/filtered alerts to
summary_channel: "cslog-alertas-resumo"

# Keywords that indicate important messages (Portuguese + English)
keywords:
  # Portuguese - Urgência
  - "urgente"
  - "crítico"
  - "critico"
  - "emergência"
  - "emergencia"
  - "ajuda"
  - "socorro"
  - "imediato"
  - "prioridade"
  - "asap"

  # Portuguese - Problemas
  - "erro"
  - "falha"
  - "falhou"
  - "quebrado"
  - "quebrou"
  - "parado"
  - "caiu"
  - "fora do ar"
  - "indisponível"
  - "indisponivel"
  - "bloqueado"
  - "travado"

  # Portuguese - Alertas
  - "alerta"
  - "atenção"
  - "atencao"
  - "cuidado"
  - "aviso"
  - "problema"
  - "incidente"
  - "bug"

  # Portuguese - Produção
  - "produção"
  - "producao"
  - "deploy"
  - "deployment"
  - "build"
  - "cliente"
  - "usuário"
  - "usuario"

  # Portuguese - Segurança
  - "segurança"
  - "seguranca"
  - "vulnerabilidade"
  - "ataque"
  - "breach"
  - "invasão"
  - "invasao"

  # English
  - "urgent"
  - "critical"
  - "emergency"
  - "help"
  - "alert"
  - "incident"
  - "down"
  - "error"
  - "failed"
  - "blocked"
  - "immediate"
  - "production"
  - "outage"

# How often to check for new messages (seconds)
check_interval: 60  # 1 minute

# Smart Monitor Settings (only used by smart monitor)
smart_filtering:
  # Enable smart filtering (dedup, pattern detection, etc.)
  enabled: true

  # Send full Claude analysis instead of filtered summary
  # Set to true to see EVERYTHING Claude analyzes (for debugging/tuning)
  # Set to false to only see filtered alerts that pass criteria
  send_full_analysis: false  # ← Send concise filtered summaries only

  # Enable interactive mode - Claude responds to questions in summary channel
  # Users can ask about recent alerts, request context, or give commands
  # Example: "What was that disk space alert about?" → Claude answers with context
  interactive_mode: true

  # How often to check for interactions in summary channel (seconds)
  # Faster checking = more responsive conversations (but more API calls)
  interaction_check_interval: 5  # Check every 5 seconds for questions

  # Minimum urgency level to send (CRITICAL, IMPORTANT, NORMAL, IGNORE)
  min_urgency_level: "IMPORTANT"

  # Don't resend similar alerts within this time window (hours)
  duplicate_window_hours: 24

  # CRITICAL alerts use shorter dedup window (hours)
  # Critical alerts are resent more frequently if issue persists
  # Set to 0 to disable dedup for CRITICAL (always send)
  # Set to 0.5 for 30 minutes, 1 for 1 hour, 2 for 2 hours, etc.
  critical_dedup_hours: 0.5  # 30 minutes (was 2h - too aggressive!)

  # How many times must an issue occur before alerting
  recurrence_threshold: 3

  # Ask Claude for final decision on borderline cases
  use_claude_decision: true

# Advanced features
advanced:
  # Enable desktop notifications (requires notify-send on Linux)
  notifications: false

  # Send startup notification to summary channel
  send_startup_notification: true

  # Include summary of recent alerts in startup notification
  # Shows what happened in the last N hours before starting
  startup_summary_hours: 1  # Look back 1 hour

  # Database paths
  database: "slack_messages.db"           # Standard monitor
  smart_database: "smart_alerts.db"       # Smart monitor

  # Enable message persistence
  persist: true

  # Enable detailed logging
  verbose: true

  # Slack Webhook URL (alternative to MCP for sending messages)
  # Get from: https://api.slack.com/apps → Your App → Incoming Webhooks
  # More reliable than MCP channel lookup
  slack_webhook_url: null  # Set to webhook URL if using webhooks

# Custom importance rules (guides Claude's analysis)
importance_rules: |
  Regras adicionais para determinar a importância das mensagens:

  1. Mensagens de usuários específicos (gerentes, líderes, etc.)
  2. Mensagens em threads onde você foi mencionado
  3. Mensagens com @ mencionando seu nome ou equipe
  4. Mensagens sobre sistemas pelos quais você é responsável
  5. Falhas de build/deployment
  6. Problemas reportados por clientes
  7. Alertas de segurança
  8. Mensagens sobre produção em horário fora do expediente
  9. Notificações de monitoramento (downtime, alta latência, etc.)
  10. Requests de aprovação urgente

  Classificar como:
  - CRÍTICO: Precisa de atenção imediata
  - IMPORTANTE: Revisar em até 1 hora
  - NORMAL: Revisar quando conveniente
  - IGNORAR: Não relevante
