slack:
  bot_token_env: SLACK_BOT_TOKEN
  summary_channel: cslog-alertas-resumo
  summary_channel_id: C09KQ5L2SF2
  critical_channel: cslog-alertas-grave
  use_socket_mode: false

channels:
  - id: C09AR0R9DG9
    label: cslog-alertas-mc
    severity_hint: NORMAL
    recurrence_threshold: 5
    critical_keywords:
      - urgent
      - indisponível
      - indisponivel
      - timeout
    ignore_patterns: []

  - id: C0891R0CET1
    label: cslog-alertas-bd
    severity_hint: IMPORTANT
    recurrence_threshold: 2
    critical_keywords:
      - database
      - banco de dados
      - erro crítico
      - replication
    ignore_patterns: []

  # NOTE: cslog-alertas-grave (C09360B9FRT) is NOT monitored as an input channel
  # It is ONLY used as the output channel for critical notifications (see slack.critical_channel below)
  # This prevents a feedback loop where the monitor reads its own notifications

  - id: C05Q5HNPLAY
    label: cslog-alertas-sc
    severity_hint: IMPORTANT
    recurrence_threshold: 4
    critical_keywords:
      - incidente
      - falha
    ignore_patterns: []

notifications:
  slack_webhook: null
  whatsapp:
    enabled: true
    service_file: whatsapp.txt
    auth_token_env: TWILIO_AUTH_TOKEN
    use_template: false

realtime_monitor:
  enabled: true
  check_interval_seconds: 30
  severity_threshold: CRITICAL  # Only send CRITICAL alerts to notification channels
  duplicate_window_minutes: 60
  lookback_minutes: 120
  llm:
    enabled: false

digest:
  enabled: true
  interval_minutes: 30
  lookback_minutes: 30
  include_filtered: true
  send_initial: true
  llm:
    enabled: false

database: smart_alerts.db
prompt_log_path: logs/claude_prompts.log
